<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <!-- BASE LINK -->
    <link name="base_link">

    </link>

    <!-- BASE FOOTPRINT LINK -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="base_footprint">

    </link>

    <!-- CHASSIS LINK -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-${cor_to_rear_of_chassis} 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length_x / 2} 0 ${chassis_height_z / 2 + caster_height}"/>
            <geometry>
                <box size="${chassis_length_x} ${chassis_width_y} ${chassis_height_z}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length_x / 2} 0 ${chassis_height_z / 2 + caster_height}"/>
            <geometry>
                <box size="${chassis_length_x} ${chassis_width_y} ${chassis_height_z}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="2.0" x="${chassis_length_x}" y="${chassis_width_y}" z="${chassis_height_z}">
            <origin xyz="${chassis_length_x / 2} 0 ${chassis_height_z + caster_height}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- LEFT WHEEL APPARATUS -->

    <joint name="left_wheel_strut_joint" type="fixed">
        <parent link="base_link" />
        <child link="left_wheel_strut" />
        <origin xyz="0 ${inter_motor_distance / 2} ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <link name="left_wheel_strut">
        <visual>
            <origin xyz="0 ${(motor_length - wheel_length) / 2} ${(wheel_radius) / 2}"/>
            <geometry>
                <box size="${(wheel_radius)} ${motor_length} ${wheel_radius}" />
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 ${(motor_length - wheel_length) / 2} ${(wheel_radius) / 2}"/>
            <geometry>
                <box size="${(wheel_radius)} ${motor_length} ${wheel_radius}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="left_wheel_strut">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${chassis_width_y / 2} ${wheel_radius}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.2" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT WHEEL APPARATUS -->

    <joint name="right_wheel_strut_joint" type="fixed">
        <parent link="base_link" />
        <child link="right_wheel_strut" />
        <origin xyz="0 -${inter_motor_distance / 2} ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <link name="right_wheel_strut">
        <visual>
            <origin xyz="0 -${(motor_length - wheel_length) / 2} ${(wheel_radius) / 2}"/>
            <geometry>
                <box size="${(wheel_radius)} ${motor_length} ${wheel_radius}" />
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 -${(motor_length - wheel_length) / 2} ${(wheel_radius) / 2}"/>
            <geometry>
                <box size="${(wheel_radius)} ${motor_length} ${wheel_radius}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="right_wheel_strut">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -${chassis_width_y / 2} ${wheel_radius}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
                <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.2" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- LEFT CASTER WHEEL LINK -->

    <joint name="left_caster_joint" type="fixed">
        <parent link="chassis"/>
        <child link="left_caster_shaft"/>
        <origin xyz="${chassis_length_x - front_of_chassis_to_caster} ${chassis_width_y / 2 - wheel_radius} ${wheel_radius * 1.5}" rpy="0 0 0"/>
    </joint>

    <link name="left_caster_shaft">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_radius}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_caster_shaft">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="left_caster_wheel_joint" type="fixed">
        <parent link="chassis" />
        <child link="left_caster_wheel" />
        <origin xyz="${chassis_length_x - front_of_chassis_to_caster} ${chassis_width_y / 2 - wheel_radius} ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="left_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="left_caster_wheel">
        <material>Gazebo/Black</material>
        <mu1 value="0.000001"/>
        <mu2 value="0.000001"/>
    </gazebo>

    <!-- RIGHT CASTER WHEEL LINK -->
    <joint name="right_caster_joint" type="fixed">
        <parent link="chassis"/>
        <child link="right_caster_shaft"/>
        <origin xyz="${chassis_length_x - front_of_chassis_to_caster} ${(chassis_width_y / 2 - wheel_radius) * -1} ${wheel_radius * 1.5}" rpy="0 0 0"/>
    </joint>

    <link name="right_caster_shaft">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_radius}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_caster_shaft">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="right_caster_wheel_joint" type="fixed">
        <parent link="chassis" />
        <child link="right_caster_wheel" />
        <origin xyz="${chassis_length_x - front_of_chassis_to_caster} ${(chassis_width_y / 2 - wheel_radius) * -1.0} ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="right_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="right_caster_wheel">
        <material>Gazebo/Black</material>
        <mu1 value="0.000001"/>
        <mu2 value="0.000001"/>
    </gazebo>

</robot>